# specific path build
trigger:
  branches:
    include:
    - master
    - feature/*
  paths: 
    exclude:
    - README.md

parameters:
  - name: deployment_target
    displayName: Deploy
    type: string
    default: dev1
    values: 
    - development
    - production
    - none

variables:
  # Base configuration
  # Add OS naming convention variables here.
  - name: system_identifier
    value: s118
  - name: system_purpose
    value: 'teacherpaymentsservice'
  - name: sln_artifact_name
    value: 'drop-sln'
  - name: build_configuration
    value: 'Release'
 
stages:
- stage: stage_build
  displayName: 'Build and Publish'
  jobs:
  - template: job/publish-os-solution.yml  
    parameters:  
      build_configuration: '${{variables.build_configuration}}'
      solution_path: 'solution/claim-additional-payments-for-teaching-qts-api.sln'
      project_path: 'solution/dqt.api/*/*.csproj'     
      test_projects_path: 'solution/*Tests/*.csproj'  
      nuget_config_path: 'solutions/doms/nuget.config'
      infra_artifact_name: '${{ variables.sln_artifact_name }}'
      sonar_key_prefix: '${{ variables.os_system_id }}'
      sonar_key_suffix: '${{ variables.os_purpose }}'