# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-settings

steps:
  # Login to DockerHub
  - script: docker login -u $(dockerId) -p $pass
    env:
      pass: $(dockerPassword)
    displayName: Login to DockerHub

  # get the latest copies from dockerhub
  - script: |
      docker pull $(dockerRegistry)/$(dockerImageName):cache-web-dependencies
      docker pull $(dockerRegistry)/$(dockerImageName):cache-test-dependencies || true
      docker pull $(dockerRegistry)/$(dockerImageName):cache-test || true    
      docker pull $(dockerRegistry)/$(dockerImageName):latest 

      docker tag dfedigital/teacher-payments-service:latest s118d01contreg.azurecr.io/teacher-payments-service:latest
      docker tag dfedigital/teacher-payments-service:cache-web-dependencies s118d01contreg.azurecr.io/teacher-payments-service:cache-web-dependencies
      docker tag dfedigital/teacher-payments-service:cache-test s118d01contreg.azurecr.io/teacher-payments-service:cache-test
      docker tag dfedigital/teacher-payments-service:cache-test-dependencies s118d01contreg.azurecr.io/teacher-payments-service:cache-test-dependencies
    displayName: pull latestest images from dockerhub and tag for ACR

# docker push ***/teacher-services-payments:cache-web-dependencies
  - task: Docker@2
    displayName: login into ACR
    inputs:
      containerRegistry: 's118d01contreg'
      command: 'login'

  - task: Docker@2
    displayName: push cache-web-dependencies container to ACR
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-web-dependencies'

  - task: Docker@2
    displayName: push cache-test-dependencies container to ACR
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-test-dependencies'

  - task: Docker@2
    displayName: push cache-test container to ACR
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'cache-test'

  - task: Docker@2
    displayName: push latest container to ACR
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 'teacher-payments-service'
      command: 'push'
      tags: 'latest'