// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dqt.datalayer.Database;

namespace dqt.datalayer.Migrations
{
    [DbContext(typeof(DQTDataContext))]
    [Migration("20210305084612_IntialTableCreation")]
    partial class IntialTableCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("dqt.datalayer.Model.QualifiedTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("HigherEducationSubjectCode")
                        .HasColumnType("text");

                    b.Property<string>("InitialTeacherTrainingSubjectCode")
                        .HasColumnType("text");

                    b.Property<string>("NationalInsuranceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("QualifiedTeachingStatusAwardDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TeacherReferenceNumber")
                        .HasColumnType("text");

                    b.Property<string>("UndergraduateSubject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QualifiedTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
