trigger: none
  # branches:
  #   include:
  #   - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-settings

steps:

  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'azdo.pipelines.cip.S118D.armfe1ef140-8bef-4043-b5ee-c449e6f951ef'
      azureContainerRegistry: '{"loginServer":"s118d01contreg.azurecr.io", "id" : "/subscriptions/8655985a-2f87-44d7-a541-0be9a8c2779d/resourceGroups/s118d01-contreg/providers/Microsoft.ContainerRegistry/registries/s118d01contreg"}'
      dockerComposeFile: '$(System.DefaultWorkingDirectory)/azure/infra/docker-compose.test.yml'
      action: 'Run a Docker Compose command'

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      containerRegistry: 's118d01contreg'
      repository: 's118d01contreg.azurecr.io'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(tag)'

  # # Build and run tests
  # - script: |
  #     docker pull $(dockerRegistry)/$(dockerImageName):cache-test-dependencies || true
  #     docker pull $(dockerRegistry)/$(dockerImageName):cache-test || true

  #     docker-compose --file=docker-compose.test.yml build
  #   displayName: Build test Docker image

  # - script: docker-compose --file=docker-compose.test.yml run --rm test
  #   displayName: Run tests on Docker
    
  # # Clean up
  # - script: |
  #     git reset --hard
  #     git clean -xdf
  #   displayName: Clean repository

  # # Publish
  # - publish: $(System.DefaultWorkingDirectory)
  #   artifact: repository
  #   displayName: Publish repository as artifact

  # # Build web dependencies
  # - script: |
  #     docker pull $(dockerRegistry)/$(dockerImageName):cache-web-dependencies || true

  #     docker build \
  #       --file=Dockerfile \
  #       --cache-from=$(dockerRegistry)/$(dockerImageName):cache-web-dependencies \
  #       --tag=local/dfe-teachers-payment-service:web-dependencies \
  #       --target=dependencies \
  #       .
  #   displayName: Build web dependencies Docker image using 'cache-web-dependencies' as cache
  #   condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  # - script: |
  #     docker build \
  #       --file=Dockerfile \
  #       --tag=local/dfe-teachers-payment-service:web-dependencies \
  #       --target=dependencies \
  #       .
  #   displayName: Build web dependencies Docker image without cache
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # # Build web
  # - script: |
  #     docker pull $(dockerRegistry)/$(dockerImageName):latest || true

  #     docker build \
  #       --file=Dockerfile \
  #       --cache-from=local/dfe-teachers-payment-service:web-dependencies \
  #       --cache-from=$(dockerRegistry)/$(dockerImageName):latest \
  #       --tag=local/dfe-teachers-payment-service:web \
  #       --target=web \
  #       --build-arg GIT_COMMIT_HASH=$(Build.SourceVersion) \
  #       .
  #   displayName: Build web Docker image using 'latest' as cache
  #   condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  # - script: |
  #     docker build \
  #       --file=Dockerfile \
  #       --cache-from=local/dfe-teachers-payment-service:web-dependencies \
  #       --tag=local/dfe-teachers-payment-service:web \
  #       --target=web \
  #       --build-arg GIT_COMMIT_HASH=$(Build.SourceVersion) \
  #       .
  #   displayName: Build web Docker image without cache
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # # Push test images
  # - script: |
  #     docker tag local/dfe-teachers-payment-service:test-dependencies $(dockerRegistry)/$(dockerImageName):cache-test-dependencies

  #     docker push $(dockerRegistry)/$(dockerImageName):cache-test-dependencies
  #   displayName: Push test dependencies Docker image for caching
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # - script: |
  #     docker tag local/dfe-teachers-payment-service:test $(dockerRegistry)/$(dockerImageName):cache-test

  #     docker push $(dockerRegistry)/$(dockerImageName):cache-test
  #   displayName: Push test Docker image for caching
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  # # Push web images
  # - script: |
  #     docker tag local/dfe-teachers-payment-service:web-dependencies $(dockerRegistry)/$(dockerImageName):cache-web-dependencies

  #     docker push $(dockerRegistry)/$(dockerImageName):cache-web-dependencies
  #   displayName: Push web dependencies Docker image for caching
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    
  # - script: |
  #     docker tag local/dfe-teachers-payment-service:web $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber)
  #     docker tag local/dfe-teachers-payment-service:web $(dockerRegistry)/$(dockerImageName):latest

  #     docker push $(dockerRegistry)/$(dockerImageName):$(Build.BuildNumber)
  #     docker push $(dockerRegistry)/$(dockerImageName):latest
  #   displayName: Push web Docker image
  #   condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
