parameters:
 - name: service_connection_name
   type: string
 - name: subscription_identifier
   type: string
 - name: subscription_purpose
   type: string
 - name: environment_id
   type: string
 - name: nuget_config_path
   type: string
 - name: connectionString_secretname 
   type: string
 - name: datalayer_project_directory
   type: string
 - name: sln_artifact_name
   type: string
 - name: vmImage 
   type: string
 - name: run_after
   type: object
   default: []

jobs:
# Deploy Funtions to Function app
# - template: ../templates/deploy-appservice-content.yml
#   parameters:
#     subscription_identifier:  '${{ parameters.subscription_identifier }}'
#     service_connection_name: '${{ parameters.service_connection_name }}'
#     environment_id: '${{parameters.environment_id}}'
#     functionapp_name: '${{ parameters.subscription_identifier }}${{parameters.environment_id}}funcappfapp'  
#     function_package_zip_name: 'dqt.api'
#     location: 'West Europe'
#     sln_artifact_name: '${{ parameters.sln_artifact_name }}'    
#     webapp_kind: 'Function'
#     create_functionapp_keys: true 
#     functionapp_key_name: DQTFunctionAppKey
#     functionapp_resourcegroup: '${{ parameters.subscription_identifier }}${{parameters.environment_id}}-funcapp'
#     keyvault_name: '${{parameters.subscription_identifier }}${{parameters.environment_id}}-secrets-kv'
#     keyvault_secret_name: DQTFunctionAppKey
   
- template: ../smoketests/run-smoketest.yml
  parameters:
    #run_after: "job_deploy_sln_${{ parameters.subscription_identifier }}${{parameters.environment_id}}funcappfapp"
    keyvault_name: '${{parameters.subscription_identifier }}${{parameters.environment_id}}-secrets-kv'
    service_connection_name: '${{ parameters.service_connection_name }}'
    WinSCPnetDLLPath: 'azure/app/smoketests/WinSCPnet.dll'
    #FileToUploadPath: '$(build.artifactstagingdirectory)\azure\app\smoketests\DqtTestData.csv'
    FileToUploadPath: '$(Pipeline.Workspace)\s\azure\app\smoketests\DqtTestData.csv'
    functionapp_name: '${{ parameters.subscription_identifier }}${{parameters.environment_id}}funcappfapp'  
    functionapp_resourcegroup: '${{ parameters.subscription_identifier }}${{parameters.environment_id}}-funcapp'
    SmokeTestScriptPath: 'azure/app/smoketests/smoketest.ps1'